version: '3.8'

services:
  client:
    build:
      context: .
      dockerfile: docker/client/Dockerfile
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=http://localhost:5000/api
    depends_on:
      - server
    networks:
      - church-network

  server:
    build:
      context: .
      dockerfile: docker/server/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - JWT_SECRET=${JWT_SECRET:-your-super-secret-jwt-key-change-this}
      - DATABASE_URL=postgresql://postgres:password@db:5432/church_program_pro
    depends_on:
      - db
    networks:
      - church-network

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=church_program_pro
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - church-network

volumes:
  postgres_data:

networks:
  church-network:
    driver: bridge