version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: docker/server/Dockerfile.dev  # Use dev Dockerfile
    ports:
      - "8000:5000"  # Use port 8000 to avoid conflict with Traccar
    environment:
      - NODE_ENV=development
      - PORT=5000
      - JWT_SECRET=your-super-secret-jwt-key-here
      - DATABASE_URL=sqlite:./dev.db
    volumes:
      - ./server/src:/app/src  # Only mount source, not dist
      - ./server/dev.db:/app/dev.db  # Mount database
      - /app/node_modules  # Preserve node_modules
    networks:
      - church-network

  client:
    build:
      context: .
      dockerfile: docker/client/Dockerfile
    ports:
      - "4000:80"  # Use port 4000 to avoid conflict with other services
    environment:
      - VITE_API_URL=http://localhost:8000/api
    depends_on:
      - server
    networks:
      - church-network

networks:
  church-network:
    driver: bridge
