services:
  - type: web
    name: program-pro-client
    runtime: static
    buildCommand: cd client && npm ci && npm run build
    staticPublishPath: ./client/dist
    routes:
      - type: rewrite
        source: /api/*
        destination: https://program-pro.onrender.com/api/*
      - type: rewrite
        source: /*
        destination: /index.html

  - type: web
    name: program-pro
    env: python
    rootDir: server
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: church-program-pro-db
          property: connectionString

databases:
  - name: church-program-pro-db
    databaseName: church_program_pro
    user: church_program_pro_user